spring:
  liquibase:
    default-schema: booking_system
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  application:
    name: booking-system
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_system_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs