booking-system:
  booking:
    expiration-time: 15m
    max-booking-term: 365
  pricing:
    markup-percent: 15
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
spring:
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  application:
    name: booking-system
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_system_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        jdbc.time_zone: UTC
springdoc:
  swagger-ui:
    path: /api/v1/swagger-ui.html
  api-docs:
    path: /api/v1/api-docs