package com.testtask.booking_system.enums;

public enum EventLogAction {
  CREATE_USER, CREATE_UNIT, DELETE_UNIT, UPDATE_UNIT, CREATE_BOOKING, BOOKING_EXPIRED, BOOKING_CANCELED,
  BOOKING_COMPLETED, PAYMENT_SUCCEEDED, PAYMENT_FAILED
}
