name: booking-storage

services:
  postgres:
    image: postgres:17
    container_name: postgresql
    environment:
      TZ: ${BOOK_SYS_POSTGRES_TIMEZONE}
      POSTGRES_USER: ${BOOK_SYS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BOOK_SYS_POSTGRES_PASS}
      POSTGRES_DB: ${BOOK_SYS_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:8.0
    container_name: redis
    command: ["redis-server", "/data/conf/redis.conf"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/data/conf/redis.conf
volumes:
  postgres_data:
  redis_data: